import { randomUUID } from 'node:crypto'
import { ResourceTemplate, type McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { McpError } from '@modelcontextprotocol/sdk/types.js'

export type ArtifactMimeType =
  'image/png' | 'image/jpeg' | 'application/x-ndjson' | 'application/json' | 'text/html'

/** An immutable, server-local snapshot; the URI never encodes a filesystem path. */
export interface ArtifactDescriptor {
  readonly uri: string
  readonly name: string
  readonly mimeType: ArtifactMimeType
  readonly size: number
  readonly expires_at: string
}

export type ArtifactUnavailable = 'too_large' | 'capacity' | 'closed' | 'unsupported_type'
export type ArtifactPublication =
  { readonly artifact: ArtifactDescriptor } | { readonly artifact_unavailable: ArtifactUnavailable }

/** Producer-only capability. It accepts generated bytes, never a path or a file reader. */
export interface ArtifactPublisher {
  readonly maxArtifactBytes: number
  publish(bytes: Uint8Array, mimeType: ArtifactMimeType, name: string): ArtifactPublication
}

const MIME_TYPES = new Set<string>([
  'image/png',
  'image/jpeg',
  'application/x-ndjson',
  'application/json',
  'text/html',
])
const TTL_MS = 15 * 60_000
const MAX_TOTAL_BYTES = 32 * 1024 * 1024
const MAX_ARTIFACTS = 32

interface Entry {
  readonly descriptor: ArtifactDescriptor
  readonly bytes: Buffer
  readonly expiresAt: number
}

/** Bounded byte snapshots shared only with clients connected to this server instance. */
export class ArtifactStore implements ArtifactPublisher {
  readonly maxArtifactBytes = 8 * 1024 * 1024
  readonly #entries = new Map<string, Entry>()
  readonly #now: () => number
  #bytes = 0
  #closed = false
  #timer: ReturnType<typeof setTimeout> | undefined

  constructor(now: () => number = Date.now) {
    this.#now = now
  }

  publish(bytes: Uint8Array, mimeType: ArtifactMimeType, name: string): ArtifactPublication {
    if (this.#closed) return { artifact_unavailable: 'closed' }
    if (!MIME_TYPES.has(mimeType)) return { artifact_unavailable: 'unsupported_type' }
    if (bytes.byteLength > this.maxArtifactBytes) return { artifact_unavailable: 'too_large' }
    this.#expire()
    if (this.#entries.size >= MAX_ARTIFACTS || this.#bytes + bytes.byteLength > MAX_TOTAL_BYTES) {
      return { artifact_unavailable: 'capacity' }
    }
    const expiresAt = this.#now() + TTL_MS
    const descriptor: ArtifactDescriptor = Object.freeze({
      uri: `stagewright://artifacts/${randomUUID()}`,
      name: name.replace(/[^a-zA-Z0-9._ -]/g, '_').slice(0, 128) || 'artifact',
      mimeType,
      size: bytes.byteLength,
      expires_at: new Date(expiresAt).toISOString(),
    })
    this.#entries.set(descriptor.uri, { descriptor, bytes: Buffer.from(bytes), expiresAt })
    this.#bytes += bytes.byteLength
    this.#scheduleExpiry()
    return { artifact: descriptor }
  }

  describe(uri: string): ArtifactDescriptor | undefined {
    this.#expire()
    return this.#entries.get(uri)?.descriptor
  }

  /** Revoke a cancelled request's snapshot; the producer's local file is untouched. */
  remove(uri: string): void {
    const entry = this.#entries.get(uri)
    if (entry === undefined) return
    this.#entries.delete(uri)
    this.#bytes -= entry.bytes.length
    this.#scheduleExpiry()
  }

  read(
    uri: string,
  ): { readonly descriptor: ArtifactDescriptor; readonly bytes: Buffer } | undefined {
    this.#expire()
    const entry = this.#entries.get(uri)
    return entry === undefined
      ? undefined
      : { descriptor: entry.descriptor, bytes: Buffer.from(entry.bytes) }
  }

  #expire(): void {
    const now = this.#now()
    for (const [uri, entry] of this.#entries) {
      if (entry.expiresAt <= now) {
        this.#entries.delete(uri)
        this.#bytes -= entry.bytes.length
      }
    }
  }

  #scheduleExpiry(): void {
    clearTimeout(this.#timer)
    this.#timer = undefined
    const expiry = Math.min(...[...this.#entries.values()].map((entry) => entry.expiresAt))
    if (!Number.isFinite(expiry)) return
    this.#timer = setTimeout(
      () => {
        this.#expire()
        this.#scheduleExpiry()
      },
      Math.max(1, expiry - this.#now()),
    )
    this.#timer.unref?.()
  }

  close(): void {
    this.#closed = true
    clearTimeout(this.#timer)
    this.#timer = undefined
    this.#entries.clear()
    this.#bytes = 0
  }
}

/** Artifact links are returned by tools; they need not be enumerated in resources/list. */
export function registerArtifactResources(mcp: McpServer, artifacts: ArtifactStore): void {
  mcp.registerResource(
    'generated_artifact',
    new ResourceTemplate('stagewright://artifacts/{id}', { list: undefined }),
    {
      title: 'Generated evidence',
      description:
        'Read an unexpired screenshot or trace produced by this server. Paths are not accepted.',
    },
    (uri) => {
      const entry = artifacts.read(uri.href)
      if (entry === undefined)
        throw new McpError(-32002, 'Artifact unavailable or expired; capture it again.')
      const { mimeType } = entry.descriptor
      return {
        contents: [
          {
            uri: uri.href,
            mimeType,
            ...(mimeType.startsWith('image/')
              ? { blob: entry.bytes.toString('base64') }
              : { text: entry.bytes.toString('utf8') }),
          },
        ],
      }
    },
  )
}
